apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-application
  template:
    metadata:
      labels:
        app: web-application
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
    spec:
      volumes:
        - name: logs
          emptyDir: {}
        - name: views
          emptyDir: {}
      securityContext:
        fsGroup: 82
      initContainers:
        - name: database-migrations
          image: backend:dev-2
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: application-config
            - secretRef:
                name: application-secret
          command:
            - "php"
          args:
            - "artisan"
            - "migrate"
            - "--force"
        - name: test
          image: backend:dev-5
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: application-config
            - secretRef:
                name: application-secret
          command:
            - "php"
          args:
            - "artisan"
            - "test"
      containers:
        - name: nginx
          imagePullPolicy: IfNotPresent
          image: frontend:dev-5
          resources:
            requests:
              cpu: 400m
              memory: 400Mi
            limits:
              cpu: 600m
              memory: 800Mi
          ports:
            - containerPort: 80
        - name: fpm
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: application-config
            - secretRef:
                name: application-secret
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/storage/logs
            - name: views
              mountPath: /var/www/html/storage/framework/views
          resources: {}
          image: backend:dev-5
          ports:
            - containerPort: 9000
